apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: inventory-staging
  source:
    repoURL: 'https://groundhog2k.github.io/helm-charts/'
    targetRevision: 0.5.13
    chart: mongodb
    helm:
      values: |
        storage:
          className: openebs-hostpath
  sources: []
  project: default
  syncPolicy:
    automated: null